from OE_objetsRessource import *

listeDesCoutsBatiments = {"Mine":Ressource(bois=50),
"Mine2":Ressource(bois=100, bronze=100),
"Mine3":Ressource(bois=500, titanium=300),
"Camp_Bucherons":Ressource(bois=50),
"Camp_Bucherons2":Ressource(bois=100, bronze=50),
"Camp_Bucherons3":Ressource(bois=200, titanium=200),
"Usine_Vehicule":Ressource(bois=100, bronze=100),
"Usine_Vaisseau":Ressource(bois=100, bronze=200),
"Usine_Vaisseau2":Ressource(titanium=300),
"Usine_Drone":Ressource(titanium=200, metasic=200),
"Centrale_Charbon":Ressource(bronze=50, charbon=50),
"Centrale_Nucleaire":Ressource(titanium=100, uranium=100),
"Grosse_Centrale_Nucleaire":Ressource(titanium=400, uranium=500),
"Eolienne":Ressource(titanium=250, bronze=250),
"Panneau_Solaire":Ressource(titanium=400, metasic=200),
"Ville":Ressource(),
"Ville2":Ressource(bois=200, bronze=200, nourriture=200, eau=200),
"Ville3":Ressource(titanium =500, uranium=500, nourriture=1000, eau=1000, bois=1000),
"Hopital":Ressource(bois=200, bronze=100, titanium=100),
"Hopital2":Ressource(metasic=250, uranium=100, eau=500, nourriture=500),
"Ecole":Ressource(bois=100, bronze=50),
"College":Ressource(point_science=50, bois=50, titanium=50),
"Universite":Ressource(point_science=200, bois=1000, metasic=200),
"Laboratoire":Ressource(point_science=150, titanium=200, uranium=100),
"Puit":Ressource(),
"Puit2":Ressource(bronze=50, titanium=50),
"Banque":Ressource(titanium=300, bronze=300),
"Ferme":Ressource(),
"Ferme2":Ressource(bronze=100, bois=100),
"Mur":Ressource(bois=50),
"Tour":Ressource(bois=150),
"Canon_Ion":Ressource(),
}

listeDAllocationBatiments = {"Mine":Ressource(allocationElectricite=5, allocationHumain=5),
"Mine2":Ressource(allocationElectricite=10, allocationHumain=10),
"Mine3":Ressource(allocationElectricite=20, allocationHumain=20),
"Camp_Bucherons":Ressource(allocationElectricite=5, allocationHumain=5),
"Camp_Bucherons2":Ressource(allocationElectricite=10, allocationHumain=10),
"Camp_Bucherons3":Ressource(allocationElectricite=20, allocationHumain=20),
"Usine_Vehicule":Ressource(allocationElectricite=10, allocationHumain=10),
"Usine_Vaisseau":Ressource(allocationElectricite=10, allocationHumain=10),
"Usine_Vaisseau2":Ressource(allocationElectricite=25, allocationHumain=20),
"Usine_Drone":Ressource(allocationElectricite=25, allocationHumain=25),
"Centrale_Charbon":Ressource(allocationHumain=5),
"Centrale_Nucleaire":Ressource(allocationHumain=15),
"Grosse_Centrale_Nucleaire":Ressource(allocationHumain=25),
"Eolienne":Ressource(allocationHumain=5),
"Panneau_Solaire":Ressource(allocationHumain=10),
"Ville":Ressource(),
"Ville2":Ressource(),
"Ville3":Ressource(),
"Hopital":Ressource(allocationElectricite=15, allocationHumain=5),
"Hopital2":Ressource(allocationElectricite=30, allocationHumain=25),
"Ecole":Ressource(allocationElectricite=10, allocationHumain=10),
"College":Ressource(allocationElectricite=15, allocationHumain=20),
"Universite":Ressource(allocationElectricite=20, allocationHumain=25),
"Laboratoire":Ressource(allocationElectricite=25, allocationHumain=20),
"Puit":Ressource(allocationElectricite=5, allocationHumain=5),
"Puit2":Ressource(allocationElectricite=10, allocationHumain=5),
"Banque":Ressource(allocationElectricite=20, allocationHumain=15),
"Ferme":Ressource(allocationElectricite=5, allocationHumain=5),
"Ferme2":Ressource(allocationElectricite=15, allocationHumain=15)
}